config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations:'users/registrations',
                                  passwords:'users/passwords',
                                  sessions:'users/sessions',
                                  
  }

  resources :friends
  
  root 'home#index'
  # root 'friends#index'
  
  #get 'home/index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  #get "home/userfriend"
  get "/userfriends", to: "home#userfriend"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  #before_action :checkLogin, only: %i[ userfriend ]
  #before_action :authenticate_user!, except: [ :index, :about ] 
  before_action :authenticate_user!



  def index
    #p /<.?>/.match("<a><b>")[0]
    @users = User.all
    @tests = ['test1', 'test2']

    @subs = getsubs

   
  end

  def about
    @user123 = current_user

    begin 
      #Job1Job.perform_later("test job1")
      #Job2Job.set(wait: 5.seconds).perform_later("test job2")
      
      # if @user123.email.eql? "dreamproperty.khanh@gmail.com"
      #   #notice: despite this msg from who, all client can receive
      # end 
      
        
    rescue =>err 
      p err 
    end
    
  end
  
  def userfriend
    @userfriends = current_user.friends.all
    
  end

  def checkLogin
    redirect_to friends_url, notice: "Please log in first !!" unless user_signed_in?
  end

  

end

app/helpers/home_helper.rb
module HomeHelper

    def getsubs
      return @subs =  User.all.to_a.sort_by{|e| e.id}.map {|u| myEncode(u.id) }
    end


    

    def myEncode(num)
      srand 101
      return "#{rand(100).to_s}ds35a#{rand(100).to_s}v93r4g6jk#{rand(100).to_s}k"+num.to_s+"wrdi98dtkh4"+rand(1000).to_s
    end
end

app/views/home/_footer.html.erb
<div
style="width: 400px; 
margin: auto; 
padding: 50px 0px;
font-size: 12px;
color: grey;

"
>



<b><i>this app copyright@ Than Trong Khanh</i></b>

</div>

app/views/home/_header.html.erb
<div class="headerTotal" >
    <div class="header P1">
    <%= link_to "Home", root_path, class:"root header_link" %>
    <%= link_to "About Me", home_about_path, class:"about header_link" %>
    <%= link_to "All Friends", friends_path, class:"friend header_link" %>
    <%= link_to "User Friends", userfriends_path, class:"userFriend header_link" %>
    <%= link_to "NewFriend", new_friend_path, class:"newFriend header_link" %>
    </div>

    <div class="header P3">
        <% if user_signed_in? %>
            Welcome : <%= current_user.email.scan(/[\w]*\@/)[0] %> !
        <% end %>
    </div>
    
    <div class="header P2">
    <%# For devise_routes %> 
    <%= link_to "Sign Up", new_user_registration_path, class:"signUp header_link" %>
    <%= link_to "Sign In", new_user_session_path, class:"signIn header_link" %>
    <%= link_to "Sign Out", destroy_user_session_path, 
        data: { "turbo-method": :delete }, class:"signOut header_link", id: "userSignOutID" %>
    <%= link_to "Edit Profile", edit_user_registration_path, class:"editProfile header_link" %>
    </div>
</div>




<div class="noticeAlert">
    <% if notice %>
        <p class="notice" style="color: orangered"> <%= notice %> </p>
    <% end %>

    <% if alert %>
        <p class="alert" style="color: red"> <%= alert %> </p>
    <% end %>

    <%# Just open and login by 3 users, refresh at route "about" each use to see %>
    <%# <div data-chat-room='Room 1' id="ChatRoom"></div> %>
</div>



<script>
    links = document.getElementsByClassName("header_link");
    
    Object.values(links).map(e => {
        e.onclick = ()=>{
            e.style.color = "red";
        }
    })

    
</script>

app/views/home/about.html.erb
<div class="About">
<h1>About me</h1>
<div class="welcomeClass"> 
    <% if @user123 %>
        <i style="padding-right: 7px">Welcome </i>
        <% if @user123.avatar.attached? %>
            <%= image_tag @user123.avatar, width:50, class: "aboutImg" %>
        <% else %>
            <%= @user123.email %> 
        <% end %>

    <% else %>
        Please login first
    <% end %>
    
</div>

</div>

<ul class="CV">
<li> Full name: Than Trong Khanh </li>
<li> Career: a ruby developer </li>
<li> Other langauges: Python, Javascript, git, html, CSS, SCSS</li>
<li> Database: postgresql, mongodb</li>
<li> location: HCM city, Vietnam</li>

<li><a href=https://khanhror001.herokuapp.com >
    app 1. devise +postgres, CRUD, reset password, real-time checking login status.</a>  </li>

<li><a href=https://khanhrorchat.herokuapp.com >
    app 2. devise +mongodb, real-time chating among user.</a>  </li>

<li> <a href=https://github.com/khanh-devos >Welcome to see my Git</a> </li>
</ul>

app/views/home/index.html.erb
<h1>Users List : </h1>

<p>Each user can have many friends shown at 
route "User_friends" or "All friends"</p>


<table class="homeIndex" id="userTableID">
    <tr>
    <th>Username</th>
    <th>Email</th>
    <th>Appearance</th>
    <th></th>
    </tr>

<% @users.sort_by{|u| u.id }.each.with_index do |e, i| %>

    <tr>
        <td><%= e.username %></td>
        <td><%= e.email %></td>
        
        <td data_appearing_on='<%= @subs[i] %>' style="color: red">
            
            <%= e.status %>
            
        </td>
        
    </tr>

    

<% end %>
</table>

<script>


</script>

app/views/home/userfriend.html.erb
<h3>
    List friends of user : <%= current_user.email %>
</h3>

<p>User can see or modify all of his or her friends, including status "archived"</p>

<select id="choice" value="all">
    <option value="all">show all</option>
    <option value="archived">show archived</option>
    <option value="public">show public</option>
    <option value="private">show private</option>
</select>
<br><br>

<% @userfriends.each do |friend| %>
    <div class="<%= "status " + friend.status %>" >
        <strong>Full name : </strong>
        <%= friend.first_name + " " + friend.last_name %>
        
        <strong>Status : </strong>
        <%= friend.status %> 
        
        <br>
        <% if friend.avatar.attached? %> 
            <strong>Avatar : </strong>
            <%= image_tag friend.avatar, width: 50 %>
            <br>
        <% end %>
        
        <%= link_to "Modify status concern here", edit_friend_path(friend) %>
        
    </div><br>
<% end %>

<script>
    choice = document.getElementById("choice");
    
    choice.onchange = function() {
        statuses = ["status public", "status private","status archived"]
        
        friends = document.getElementsByClassName("status");
        Object.values(friends).map(e => e.style.display = 'none');
        
        statuses.map(item => {    
            if (choice.value === "all"){
                Object.values(friends).map(e => e.style.display = 'block');
            }
            else if (item.includes(choice.value)){
                friends = document.getElementsByClassName(item)
                Object.values(friends).map(e => e.style.display = 'block');
            }
            
            
        })
    }    
</script>